### ISSUE TITLE
Database Management

### ISSUE THREAD

**Issue by thisisayush** [vipulgupta2048/scrape#35]
Proposed Database Management:

- Creation of database file (e.g. db.py) which allows basic database operations like ```connect()```, and utilities like ```checkUrlExists()``` (for reference, [thisisayush/scrape/](https://github.com/thisisayush/scrape/blob/Scrapyd/thisisayush/news18/news18/db.py)
- Automatic Numbering and assignment of spiders in ```sites``` saving time to recreate envconfig.py in every system the repo is cloned to.
- Additional Table Column ```scraped_time```, which stores the time ```NOW()``` of when the entry was added to the database.
- Additional Table ```Logs``` which stores daily statistics of spiders run.

**Comment by ATB00ker** [comment]
(1) Please explain the reason for the change proposed. [First point]
(2) I agree with your point; but how do you propose to automate the process. [Second point]
(3) Please explain the reason for the change proposed. [Third point]
(4) I agree with the point; it will be useful to make this change. [fourth point]

**Comment by thisisayush** [comment]
(1) It saves bandwidth. Before sending request to scrape, if it is checked by the spider itself if the link was scraped, it can save lots of bandwidth and time (this is where a handy method like ```checkUrlExists()`` comes in handy)
(2) I have implemented a technique in News18 Project in ```News18Pipeline```, take a look.
(3) I have no idea of what's the need, but I feel it'll be required in reporting to see how many urls were crawled in a given day.
(4) Yeah, Again do have a look at News18Project, I have been experimenting a lot :)

P.S. News18Project refers to Scrapyd Branch/thisisayush/news18

**Comment by ATB00ker** [comment]
(1)  `connect()` is used in pipelines of the scraper, it does the exact same thing i, do not see the reason to move it out of the pipelines file. `checkUrlExists()` looks like something interesting, but it would require to save the data somewhere, which is a waste of space since the data is already saved in the database, simple check in the spider would yield in same result with less resources, (refer the updated code for the same).
(3) newsDate contains date of the news, simply use that to report how many were scraped in that day. (Working with the obvious logic that the news site wouldn't report a future or a past news.). Editing the database without a critical reason seems wrong in my opinion.

> (4) Yeah, Again do have a look at News18Project, I have been experimenting a lot :)
>>> I am planning to make a new table and insert the currently saved variable from .log file to the database, it do not see the need of experimentation in this, all though, it you have a more efficient way that the code that you have refered, please inform, i will check it out.

**Comment by thisisayush** [comment]
> but it would require to save the data somewhere,
It doesn't store the data but queries the database and returns Boolean accordingly.

>  newsDate contains date of the news, simply use that to report how many were scraped in that day. 
It's good to report news published that day not the news scraped that day, We are running spiders at this time which are fetching news long before the project was started. I don't understand how will you track date using ```newsDate```

>  it you have a more efficient way that the code that you have refered,
I am not talking about storing All Error Logs and scrapy logs in database! I am talking about spider run logs. Check below for what I have implemented:
```
news18db=# SELECT * FROM logs;
 id | site |      start_time       |       end_time        | urls_parsed | urls_scraped | urls_dropped | urls_stored | shutdown_reason 
----+------+-----------------------+-----------------------+-------------+--------------+--------------+-------------+-----------------
  1 |    1 | 03:42:03.287638+05:30 | 13:09:51.012188+05:30 |       31878 |        31850 |           16 |       30417 | finished
(1 row)

```

**Comment by ATB00ker** [comment]
> but it would require to save the data somewhere.
> > It doesn't store the data but queries the database and returns Boolean accordingly.
> > > That's that has been already implemented (Read the latest code and do elaborate the difference.)

> newsDate contains date of the news, simply use that to report how many were scraped in that day.
> > It's good to report news published that day not the news scraped that day, We are running spiders at this time which are fetching news long before the project was started. I don't understand how will you track date using newsDate.
> > >  - 'You' are scraping the long old news.
> > >  - I think the current implementation tackles the same problem. 

> it you have a more efficient way that the code that you have refered,
> > I am not talking about storing All Error Logs and scrapy logs in database! I am talking about spider run logs. Check below for what I have implemented.
> > > That doesn't look like a method. It looks like a result. In tabular form. I have agree to moving the info logs to database, they will look like a table too. :)

**Comment by thisisayush** [comment]
> That has been already implemented (Read the latest code and do elaborate the difference.)
> > I guess I explained it already in #34 

> I think the current implementation tackles the same problem.
> > The Spider Didn't run or server under maintenance problem, Hey! I am here too :-)

>  I have agree to moving the info logs to database
> > Strongly Recommended not to! Can be 1000's of rows of logs for a single spider run!

> That doesn't look like a method. It looks like a result. In tabular form.
> > It is a result of a query so I guess it looks like one. If you want the method, say 4 counters updating at certain stage, certain functions which starts and ends the logs, and yeah database connectivity and lots of programming!

**Comment by atb00ker** [comment]
All of the issues look solved, Closing! :)
