### ISSUE TITLE
Setup automation

### ISSUE THREAD

**Issue by atb00ker** [vipulgupta2048/scrape#57]
Setup needs to be automated, use of ansible is preferred for this purpose.
- Download/Install/Setup all the requirements for the OS:
  - python==3.5
  - postgres
  - gunicorn
  - nginx
- Python Libraries:
   - python-dateutil
   - scrapy 

Note: List might need to be modified.

**Comment by thisisayush** [comment]
Automation Script added in 993f87a68c675961541b564c5175c15aa8eeaefa
