### ISSUE TITLE
Bug report: When connection is lost, the re connection causes another log_table entry.

### ISSUE THREAD

**Issue by atb00ker** [vipulgupta2048/scrape#61]
**Problem:** If the connection fails, automatically reconnecting the database causes a new entry in the pipelines to be made, the old entry remains there, without any closing time!

**Suggested Solution:**  If making connection is required, run the line which makes the connection and not the entire function!

**Comment by thisisayush** [comment]
A new reconnection technique and a new method ```end_log``` that ends log using log id has been added in commit c4cf46d042c0a48f81b38c866d1cd69b72850fcc 
Seems Fixed Now . Close the issue after verifying:)

**Comment by thisisayush** [comment]
No response has been received, closing issue now.
